.github/workflows/ci.cleanup.yml, .github/workflows/ci.yml, src/mixins/i18n-lit-element.ts
https://jira.camptocamp.com/browse/GSLUX-457
Add new workflow to deploy on github pages.
=> GSLUX-457: Deploy to gh pages

src/App.vue, src/components/background-selector/background-selector.vue, src/components/layer-manager/layer-manager.vue, src/components/remote-layers/remote-layers.mapper.ts, src/components/remote-layers/remote-layers.service.ts, src/composables/map/ol.synchronizer.ts, src/composables/themes/themes.composable.ts, src/services/state-persistor/state-persistor-layer.mapper.spec.ts, src/services/state-persistor/state-persistor-layer.mapper.ts, src/services/state-persistor/state-persistor-rules-read.helper.spec.ts, src/services/state-persistor/state-persistor-rules-read.helper.ts, src/services/state-persistor/state-persistor-rules-write.helper.spec.ts, src/services/state-persistor/state-persistor-rules-write.helper.ts, src/services/state-persistor/state-persistor.model.ts, src/services/state-persistor/state-persistor.service.ts, src/services/state-persistor/storage/storage-proxy.spec.ts, src/services/state-persistor/storage/storage-proxy.ts, src/services/state-persistor/storage/storage.helper.spec.ts, src/services/state-persistor/storage/storage.helper.ts, src/services/state-persistor/storage/url-storage.spec.ts, src/services/state-persistor/storage/url-storage.ts, src/stores/map.store.spec.ts, src/stores/map.store.ts
https://jira.camptocamp.com/browse/GSLUX-552
=> GSLUX-552: Permalink

src/App.vue, src/assets/main.css, src/components/background-selector/background-selector.vue, src/components/common/dropdown-list.model.ts, src/components/common/dropdown-list.spec.ts, src/components/common/dropdown-list.vue, src/components/nav-bars/language-selector.spec.ts, src/components/nav-bars/language-selector.vue, src/services/state-persistor/state-persistor-lang.service.ts, src/services/state-persistor/state-persistor-layers.service.ts, src/services/state-persistor/state-persistor-rules-read.helper.spec.ts, src/services/state-persistor/state-persistor-rules-read.helper.ts, src/stores/app.store.ts, vitest.setup.ts
https://jira.camptocamp.com/browse/GSLUX-564
- restore and persist lang from url or from storage
- added new app store to store selected lang by user
- improve UI for language selector in nav bar
- improve dropdown list to be reusable also in navbar
=> GSLUX-564: Restore and persist lang

package-lock.json, package.json, src/components/layer-tree/layer-tree-node.spec.ts, vitest.setup.ts
https://jira.camptocamp.com/browse/GSLUX-580
PR for updating ol dep. version in package.json
=> GSLUX-580: fix ol version

src/App.vue, src/components/catalog/catalog-tab.vue, src/components/footer/button-icon.vue, src/components/footer/button-link.vue, src/components/footer/footer-bar.vue, src/components/header/header-bar.vue, tailwind.config.cjs
https://jira.camptocamp.com/browse/GSLUX-597
PR adds the footer toolbar and makes it responsive. Also refactors header into a proper component.
Buttons without functionality yet are displayed in gray for now, to easier identify what is still missing. `class="text-gray-300"` should be removed once a tool is implemented.
=> GSLUX-597: Add footer

.github/workflows/ci.yml
Comment dysfunctional workflow step for now to not block other steps. For error, see [here](https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/actions/runs/5821616728/job/15784412278)
=> GSLUX-635: Comment lib workflow for now

bundle/lux.dist.mjs, bundle/lux.dist.umd.js, bundle/style.css, src/bundle/lib.ts
https://jira.camptocamp.com/browse/GSLUX-642
add exports for use in V3
=> share background layer service for use in v3

cypress/e2e/draw-bar.cy.ts, cypress/support/commands.ts, src/components/footer/button-text.vue, src/components/footer/footer-bar.vue, src/components/footer/toolbar-draw.vue, src/composables/draw/draw-interaction.composable.ts, src/composables/draw/draw.composable.ts, src/composables/draw/drawn-features.composable.ts, src/stores/draw.store.ts
https://jira.camptocamp.com/browse/GSLUX-689
PR sets up the base for the draw tools, including:
- draw.composable: creates the ol draw interactions and handles their active state 
- draw-interaction.composable: generates each ol draw interaction
- draw.store: stores the draw tools UI states
- drawn-features.composable: manipulates features drawn on the map
TODO:
=> GSLUX-689: Set up draw tools

cypress/e2e/draw-bar.cy.ts, cypress/e2e/footer-bar.cy.ts, src/assets/main.css, src/composables/draw/draw-interaction.composable.ts, src/composables/draw/draw-tooltip.ts, src/stores/app.store.ts
https://jira.camptocamp.com/browse/GSLUX-703
PR adds the measure tooltip (logic corresponding to v3 DrawController.onDraw...Start functions).
=> GSLUX-703: Add draw tooltip

.github/workflows/ci_bundle.yml
=> test trigger on merge

cypress/e2e/style-selection.cy.ts, src/services/state-persistor/state-persistor-bgstyle.service.ts
https://jira.camptocamp.com/browse/GSLUX-721
style definition is also written by mistake for non-vector background layers
=> GSLUX-721: write style def only for vector layers

.github/workflows/ci_bundle.yml
=> clean workflow

.github/workflows/ci_bundle.yml
=> verbose output

.github/workflows/ci_bundle.yml
=> Dummy main pr test

.github/workflows/#ci_auto_tag.yml#, .github/workflows/ci_bundle.yml
upon push on main, branch a tag will be generated by CI:
- <merged_branch_name>_CI_<short_commit> if commit is a merge
- <main_branch_name>_CI_<short_commit> if commit is not a merge (direct push on main forbidden by repo conf ??)
=> Fine-tune workflow for tag generation on main branch pushes

cypress/e2e/draw/draw-bar.cy.ts, cypress/e2e/draw/draw-feat-line.cy.ts, cypress/e2e/draw/draw-feat-polygon.cy.ts, cypress/e2e/draw/draw-notifications.cy.ts, package-lock.json, package.json, src/components/alert-notifications/alert-notifications.vue, src/components/alert-notifications/notification-item.vue, src/composables/draw/draw-notifications.composable.ts, src/composables/draw/draw.composable.ts, src/stores/alert-notifications.store.model.ts, src/stores/alert-notifications.store.spec.ts, src/stores/alert-notifications.store.ts
https://jira.camptocamp.com/browse/GSLUX-709
Display help message for each type of drawing.
WARNING: this PR is based on GSLUX-728, should rebase on main before merging
=> GSLUX-709: Notification messages on draw

cypress/e2e/background-selection.cy.ts, cypress/e2e/layers-selection.cy.ts, src/components/draw/feature-item.vue, src/components/draw/feature-menu-popup.vue
=> are tests fixed ?

cypress/e2e/draw/draw-panel.cy.ts, src/components/draw/draw-panel-features.vue, src/components/draw/feature-edit-info.vue, src/components/draw/feature-item.vue, src/components/draw/feature-sub-content.vue
https://jira.camptocamp.com/browse/GSLUX-742
PR updates the feature properties (label & description), based on #151
=> GSLUX-742: Modify feature properties

src/bundle/lib.ts, src/main.ts
https://jira.camptocamp.com/browse/GSLUX-744
PR should fix the build broken by #155 import statement
=> GSLUX-744 bis: Fix import for build

.env.staging
https://jira.camptocamp.com/browse/GSLUX-744
PRs adapts staging URL value for gh-pages.
=> GSLUX-744 bis 2: Fix VITE_ELEVATION_URL for gh-pages

.env, .env.development, .env.e2e, .env.staging, cypress/e2e/auth/auth.cy.ts, cypress/e2e/header-bar.cy.ts, package-lock.json, package.json, src/components/auth/auth-form.spec.ts, src/components/auth/auth-form.vue, src/components/header-bar/header-bar.vue, src/services/auth/auth.service.spec.ts, src/services/auth/auth.service.ts, src/services/state-persistor/state-persistor-app.service.ts, src/stores/app.store.ts, src/stores/user-manager.store.model.ts, src/stores/user-manager.store.ts
https://jira.camptocamp.com/browse/GSLUX-748
Plug the authentication form to the api.
For auto login with cookies => this will be address in https://camptocamp.atlassian.net/browse/GSLUX-749
=> GSLUX-748: Auth plug api

src/components/draw/draw-panel-features.vue, src/services/state-persistor/state-persistor-features.mapper.ts, src/stores/draw.store.ts
https://jira.camptocamp.com/browse/GSLUX-741
=> GSLUX-741 fix z-order

src/bundle/lib.ts
https://jira.camptocamp.com/browse/GSLUX-770
Export storage helper in lib to be used in v3.
=> GSLUX-770: Fix draw and layers in permalink v3

src/bundle/lib.ts
GITLAB-41
https://gitlab.geoportail.lu/cadastre_intern/mapv3/-/issues/41
Expose url storage
=> export url storage in the lib

src/services/state-persistor/state-persistor-layer.mapper.spec.ts, src/services/state-persistor/state-persistor-layer.mapper.ts, src/services/state-persistor/state-persistor-layers.service.ts
https://gitlab.geoportail.lu/cadastre_intern/mapv3/-/issues/42
The layer order saved in the url is wrong
=> wrong layer order in url

src/bundle/components/profile_v3/profile-infos_v3.vue
GITLAB-44
https://gitlab.geoportail.lu/cadastre_intern/mapv3/-/issues/44
it allows to show profile when geometry is a multilinestring
=> allow multilinestring

src/components/slider/slider-comparator.vue
https://gitlab.geoportail.lu/cadastre_intern/mapv3/-/issues/45
the slider should be moved when map size is changing
=> reflect the ratio when map size is updated

src/components/common/slider-range/slider-range-thumb.vue
https://gitlab.geoportail.lu/cadastre_intern/mapv3/-/issues/47
Set real default values.
=> set better default values

.env
https://gitlab.geoportail.lu/cadastre_intern/mapv3/-/issues/53
We want to proxy only wms http requests.
=> GITLAB-53: In production we want to proxy only http server

src/components/theme-selector/theme-selector.service.ts, src/stores/config.store.ts
https://gitlab.geoportail.lu/cadastre_intern/mapv3/-/issues/63
=> GITLAB-63: Manage blank in theme name

cypress/e2e/3d-viewer/link-to-3d-viewer.cy.ts, src/components/map-controls/map-3d.vue, src/services/state-persistor/state-persistor-map.service.ts, src/stores/map.store.ts
https://jira.camptocamp.com/browse/GSLUX-780
PR takes rotation into account when opening the 3D viewer.
=> GSLUX-780: Add rotation to 3d URL generation
