.husky/pre-commit
package.json

husky pre-commit hooks for git were broken after husky upgrade v4 -> v8
https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/commit/7c1650921c357e5cd7a83bf35a5f340a1a274f16#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L43
fixed now.

fix husky pre-commit hooks after change from v4 to v8

---

src/components/catalog/catalog-tree.vue
src/components/layer-manager/layer-item/layer-item-background.vue
src/components/layer-manager/layer-manager.vue
src/components/layer-metadata/layer-metadata.vue
src/components/layer-tree/layer-tree-node.vue
src/components/layer-tree/layer-tree.model.ts
src/components/layer-tree/layer-tree.service.ts
src/components/remote-layers/remote-layers.mapper.ts
src/composables/layers/layers.composable.ts
src/composables/themes/themes.composable.ts
src/services/layer-metadata/layer-metadata.service.spec.ts
src/services/layer-metadata/layer-metadata.service.ts
src/stores/metadata.store.ts

https://jira.camptocamp.com/browse/GSLUX-578
PR displays metadata from layermanager (which was lost when refactoring #26). Now also handles bgLayers which was not the case before.
It refactors the metadata store to only store the metadata id to work with nodes and layers.

GSLUX-578: Display metadata from layermanager

---

public/assets/locales/client.de.json
public/assets/locales/client.en.json
public/assets/locales/client.fr.json
public/assets/locales/client.lb.json
src/App.vue
src/__fixtures__/background.config.fixture.ts
src/components/layer-manager/layer-manager.vue
src/components/layer-panel/layer-panel.vue
src/components/style-selector/medium-style-item.vue
src/components/style-selector/medium-style-selector.vue
src/components/style-selector/simple-style-selector.spec.ts
src/components/style-selector/simple-style-selector.vue
src/components/style-selector/style-selector.vue
src/composables/map/ol.synchronizer.ts
src/composables/mvt-styles/mvt-styles.composable.ts
src/composables/mvt-styles/mvt-styles.model.ts
src/services/state-persistor/state-persistor-bgstyle.service.ts
src/services/styles/styles.model.ts
src/services/styles/styles.service.ts
src/stores/app.store.ts
src/stores/style.store.ts

https://jira.camptocamp.com/browse/GSLUX-592
simple and medium style editors and reset are connected to the style store
there is a difference to prod, since the style is different if loaded without custom style or reset to custom style. This is due to the fact that the styles apparently have diverged and the custom default style is no longer identical to the online default style. This difference can be seen in the screenshots below.
This glitch shall be fixed once the clients have checked the style.
default style:
default style after reset:
custom style:

GSLUX-592: Style Editor Medium

---

bundle/lux.dist.mjs
bundle/lux.dist.umd.js
cypress/e2e/layers-selection.cy.ts
src/components/layer-panel/layer-panel.vue

https://jira.camptocamp.com/browse/GSLUX-628
Lorsqu'aucune couche n'est sélectionnée, il ne faut pas afficher le compteur de couches sélectionnées dans le label de l'onglet "Mes couches".

GSLUX-628: Counter Label MyLayer

---

bundle/lux.dist.mjs
bundle/lux.dist.umd.js
bundle/style.css
cypress/e2e/layers-selection.cy.ts
cypress/e2e/main.elements.cy.ts
src/assets/main.css
src/components/common/modal-dialog.vue
src/components/layer-metadata/layer-metadata.vue
src/components/layer-tree/layer-tree-node.vue
src/components/remote-layers/remote-layers.vue
tailwind.config.cjs

https://jira.camptocamp.com/browse/GSLUX-571
PR adds a generic modal dialog and uses it for remote layers and layer metadata. 
The title is currently displayed in one consistent layout, while the v3 has different layouts depending on the modal.
The backdrop is now always displayed, while the v3 only displays it for the remote layers modal.
Todos:

GSLUX-571: Add a generic modal dialog

---

bundle/lux.dist.mjs
bundle/lux.dist.umd.js
src/components/layer-manager/layer-manager.vue
src/stores/app.store.ts

https://jira.camptocamp.com/browse/GSLUX-622
PR changes the app store's `toggleStyleEditorPanel` function to a `openStyleEditorPanel` to better fit current use case in v3.

GSLUX-622: Style selector

---

bundle/lux.dist.mjs
bundle/lux.dist.umd.js
src/composables/mvt-styles/mvt-styles.composable.ts
vite.config.ts

https://jira.camptocamp.com/browse/GSLUX-622
Follow-up PR to #60 to fix following error in v3:
`Access to fetch at 'http://localhost:8080/uploadvtstyle' from origin 'https://migration.geoportail.lu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
Makes backend urls used for styles relative for lib to work in v3.
Uses vite proxy to send requests to local backend for dev.
Note : In v3 this PR should currently not have an impact on the functionality, as the legacy style selector is used. It should however prevent the error messages in the console which are triggered by the v4-lib in the background.

GSLUX-622 (Fix): Make backend urls relative for lib

---

.github/workflows/ci.yml

PR should build lib, increment version in package.json and create a tag with corresponding version, when merging PRs on main.
When testing on the `pull_request` event, I had the [error](https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/actions/runs/5575820967/jobs/10186249989#step:6:24) "nothing to commit" because of a detached HEAD. Not sure if there will be the same issue when merging on main.

GSLUX-635: Add workflow step to build and tag lib

---

.github/workflows/ci.yml

PR should fix building lib in CI by setting git config before `npm version patch`, which actually creates a commit by itself.

GSLUX-635: Fix lib build in CI

---

bundle/lux.dist.mjs
bundle/lux.dist.umd.js
cypress/e2e/header-bar.cy.ts
cypress/e2e/permalink/layersOpen.cy.ts
cypress/e2e/side-panel.cy.ts
src/components/catalog/catalog-tab.vue
src/components/header/header-bar.vue
src/components/layer-panel/layer-panel.spec.ts
src/components/layer-panel/layer-panel.vue
src/components/theme-selector/theme-grid.vue
src/components/theme-selector/theme-selector.spec.ts
src/components/theme-selector/theme-selector.vue
src/stores/app.store.ts

To test in v3: https://github.com/Geoportail-Luxembourg/geoportailv3/pull/3082
https://jira.camptocamp.com/browse/GSLUX-633
When clicking on theme button in the header, it should: 
- display the side panel (if not already displayed) and display the theme grid
- if the side panel is visible but the catalog tab is not selected, it should select the catalog tab and display the theme grid
- if the side panel and the theme grid are already visible, it should hide the side panel

GSLUX-633: On click theme button in header

---

bundle/lux.dist.mjs
bundle/lux.dist.umd.js
src/bundle/lib.ts

I forgot to rebuild the library...

rebuild library

---

bundle/lux.dist.mjs
bundle/lux.dist.umd.js
src/stores/map.store.spec.ts
src/stores/map.store.ts

https://jira.camptocamp.com/browse/GSLUX-646
the function to remove all layers is useful for switching to 3d mesh in v3 (see https://github.com/Geoportail-Luxembourg/geoportailv3/pull/3091 - dev in progress)

Gslux 646 remove ngeo bg manager

---

src/assets/ol.css
src/components/catalog/catalog-tree.vue
src/components/layer-manager/layer-item/layer-item.vue
src/components/layer-manager/layer-manager.vue
src/components/map-controls/map-3d.vue
src/components/map/map-container.vue
src/composables/layers/layers.composable.ts
src/composables/themes/themes.composable.ts
src/services/layer-metadata/layer-metadata.service.ts
src/stores/config.store.ts
src/stores/map.store.ts

https://jira.camptocamp.com/browse/GSLUX-642
a state has been introduced for 3d mode which can be controlled from v3
3d items can now be displayed in the catalog and in the layer tree.
a dummy button is used for toggling 3d mode in v4

Gslux 642 3d catalog

---

README.md
cypress/e2e/language-selection.cy.ts
cypress/e2e/layers-selection.cy.ts
cypress/e2e/slider-comparator.cy.ts
cypress/e2e/theme-selection.cy.ts
package-lock.json
package.json

- update the REAME (add info for using lux as a lib with Custom Elements)
- update deps

Update readme and some deps

---

.github/workflows/ci_bundle.yml

Dummy main pr test

---

.github/workflows/ci_bundle.yml
README.md
package.json

automatic tag generation on PRs
the workflow was tested with the sub PR below:
https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/132
this created correctly the release https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/releases/tag/GSLUX-635_automate_tag_on_merge_test_merge_CI_8e1839f
the manual workflow (npm run tag) was tested with this release:
https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/releases/tag/GSLUX-635_automate_tag_on_merge_TAG_c1576cd
checks:

trigger auto tag on PR edit and merge

---

.env
.env.development
.env.e2e
.env.staging
src/services/layer-metadata/layer-metadata.service.ts

https://jira.camptocamp.com/browse/GSLUX-760
- now using urls coming from .env for metadata and legends
- use relative urls for production mode
**TODO in v3 => update package.json with new release when merged**

GSLUX-760: Fix use relative urls for metadata

---

.env
.env.development
.env.e2e
.env.staging
src/components/draw/feature-menu-popup.vue
src/services/export-feature/export-feature-gpx.spec.ts
src/services/export-feature/export-feature-gpx.ts
src/services/export-feature/export-feature-kml.spec.ts
src/services/export-feature/export-feature-kml.ts
src/services/export-feature/export-feature-shapefile.spec.ts
src/services/export-feature/export-feature-shapefile.ts
src/services/export-feature/export-feature.service.ts
src/services/export-feature/export-feature.ts
src/services/export-feature/ol-format-gpx.ts
src/services/utils.spec.ts
src/services/utils.ts

https://jira.camptocamp.com/browse/GSLUX-737
Export drawn feature as gpx, kml and shapefile + fix export gpx for circle and polygon (does not work in prod).
Export gpx and kml does not call api anymore.
NB. use chrome plugin for CORS policy when exporting to shapefile (you need v3 running on localhost:8080)

GSLUX-737: Export drawn feature as gpx, kml and shapefile

---

cypress/e2e/draw/draw-feat-circle.cy.ts
cypress/e2e/draw/draw-feat-line.cy.ts
cypress/e2e/draw/draw-feat-polygon.cy.ts
src/bundle/lib.ts
src/components/draw/feature-measurements.vue
src/composables/draw/draw-tooltip.ts
src/composables/draw/draw-utils.ts
src/composables/draw/drawn-features.composable.ts
src/composables/draw/edit.composable.ts
src/directives/format-area.directive.ts
src/directives/format-length.directive.ts
src/main.ts
src/services/common/formatting.utils.ts
src/services/common/measurement.utils.ts
src/services/draw/drawn-feature.ts
src/services/export-feature/export-feature.ts
src/services/state-persistor/state-persistor-features.mapper.ts
src/services/state-persistor/utils/FeatureHash.ts
src/services/state-persistor/utils/FeatureStyleHelper.ts
src/stores/draw.store.ts

https://jira.camptocamp.com/browse/GSLUX-743
PR enables editing circle geometries and calculates circle measurements. It refactors the measurement formatting further into directives. Note that vertices are not highlighted anymore like in v3, but the default ol modification style is applied.
There is one remaining issue regarding the circle radius which is not an exact value. Due to `resolutionFactor` applied before `circle.setRadius()` it is approximate and decreases on multiple submits or app reloads:
- submitted values in the radius input are also approximate on prod
- submitting same values multiple times also has an issue on prod
- reloading the app on prod may work because encoded polygon geometries are not converted back to circles
I didn't manage to fix this issue (which is …

GSLUX-743: Modify circle geometries

---

.babelrc
.env
.env.development
.env.e2e
.env.staging
README.md
package.json
src/assets/main.css
src/bundle/lib.ts
src/components/auth/auth-form.spec.ts
src/components/auth/auth-form.vue
src/services/auth/auth.service.spec.ts
src/services/auth/auth.service.ts
vite-dist.config.ts

https://jira.camptocamp.com/browse/GSLUX-749
Finalize auth form component.
- improve/fix lib build for dev
- allow authentication through localhost:8080 in standalone app
- fix/adapt auth-form component to be integrated in v3
- added new doc in readme regarding auth configuration

GSLUX-749: Auto auth with cookies and adapt for v3

---

cypress/e2e/header-bar.cy.ts
src/App.vue
src/bundle/lib.ts
src/components/layer-manager/layer-item/layer-item-background.vue
src/stores/app.store.ts

https://jira.camptocamp.com/browse/GSLUX-639
PR exports the style panel for integration in v3 and removes a condition in v4 app that does not seem necessary anymore.

GSLUX-639: Export style panel

---

cypress/e2e/draw/draw-feat-line.cy.ts
cypress/e2e/layers-selection/layers-selection-catalog.cy.ts
src/assets/main.css
src/components/draw/feature-edit-linestyle-item.vue
src/components/draw/feature-sub-wrapper.vue
src/composables/draw/draw-interaction.composable.ts
src/services/utils.ts

https://jira.camptocamp.com/browse/GSLUX-765
Fix:
- style on button: was purple(why???) with exaggerated rounded corner too different from prod
- enable Escape keyup handler when drawing
- update coordinates for drawing modale when modifying drawn feature

GSLUX-765: FIX drawing

---

src/bundle/components/profile_v3/profile-infos_v3.vue
src/bundle/components/profile_v3/profile-routing_v3.vue
src/bundle/lib.ts
src/bundle/stores/profile-infos_v3.store.ts
src/bundle/stores/profile-routing_v3.store.ts
src/components/feature-elevation-profile/feature-elevation-profile.vue
src/composables/map/profile-position.composable.ts
src/services/ol-layer/ol-layer-feature-position.helper.ts

https://jira.camptocamp.com/browse/GSLUX-767
- add new component to be used in v3 for profile support in v3 Routing
- improve performances display of geomarker on mark (added `useSpatialIndex`, `declutter`, `updateWhileAnimating`, `updateWhileInteracting` ol props on layer anf feature)
- add new possibility to deactivate profile through a ref passed to the composable

GSLUX-767: Support for profile routing in v3

---

src/bundle/components/profile_v3/profile-draw_v3.vue
src/bundle/components/profile_v3/profile-measures_v3.vue
src/bundle/stores/profile-draw_v3.store.ts
src/bundle/stores/profile-measures_v3.store.ts
src/components/feature-elevation-profile/feature-elevation-profile.vue
src/composables/map/profile-position.composable.ts

https://jira.camptocamp.com/browse/GSLUX-769
Enable reset profile measures data (reset and show empty graph) when profile measure is reset/hidden/closed in v3.

GSLUX-769: FIX for profile measures in v3

---

src/components/map/map-container.vue
src/services/state-persistor/state-persistor-features.service.ts

https://jira.camptocamp.com/browse/GSLUX-766
PR adds a condition to init v4 draw logic only in v4 and not v3 (where it has not been integrated yet).
This caused a bug when deleting drawn features when using permalinks.

GSLUX-766: Do not init useDraw in v3

---

src/assets/ol.css
src/components/map-controls/rotate-control.vue
src/components/map/map-container.vue
src/composables/map/map.composable.ts

https://gitlab.geoportail.lu/cadastre_intern/mapv3/-/issues/37
Keep the same rotation key as in V3 and add the missing rotation control

Manage rotation with ctrl key

---

src/bundle/lib.ts

https://gitlab.geoportail.lu/cadastre_intern/mapv3/-/issues/43
Need to export the class, because snapped url is built in the constructor

export UrlStorage in api

---

src/components/layer-panel/layer-panel.vue

https://gitlab.geoportail.lu/cadastre_intern/mapv3/-/issues/32
Hides the component instead of recreating it.
That means, we can now switch from catalog to layer tab without loosing the opened categories.

GITLAB-32 : hides the component instead of recreating it

---

src/services/ol-layer/ol-layer-wms.helper.ts

https://gitlab.geoportail.lu/cadastre_intern/mapv3/-/issues/34
authentication cookies are lost when no-cors mode is not set

GITLAB-34: no-cors header

---

cypress/e2e/theme-selection.cy.ts
src/components/header-bar/header-bar.vue
src/components/theme-selector/theme-selector-button.vue
src/components/theme-selector/theme-selector.vue
src/stores/config.store.ts

Fixes issue where theme is not selected if it is unknown to the application when not logged in
https://gitlab.geoportail.lu/cadastre_intern/mapv3/-/issues/51
Fixes issue where theme is not selected if it is unknown to the application when not logged in

Fixes theme selection

---

cypress/e2e/3d-viewer/link-to-3d-viewer.cy.ts
src/components/map-controls/map-3d.vue

https://jira.camptocamp.com/browse/GSLUX-780
Todos:

GSLUX-780: Add bgLayer to 3d URL generation
